In [1]:
from octo.data.cobot.standard_dataload import load_dataset_from_tfrecords, load_dataset_from_hdf5
from octo.data.utils.format import pytree_display
from dlimp.dataset import _wrap


dataset_path = '/root/autodl-tmp/cobot_magic'

if __name__ == '__main__':
    dataset = _wrap(load_dataset_from_hdf5, False)(dataset_path)
    print(type(dataset))
    print('successfully loaded dataset')
    for item in dataset.take(1):
        pytree_display(item)
        print('time 0')
        print('action', item['action'][0])
        print('base', item['base_action'][0])
        print('instruction', item['instruction'][0])
        print('qpos', item['qpos'][0])
        print('qvel', item['qvel'][0])
        print('time 1')
        print('action', item['action'][1])
        print('base', item['base_action'][1])
        print('instruction', item['instruction'][1])
        print('qpos', item['qpos'][1])
        print('qvel', item['qvel'][1])
        print('time 2')
        print('action', item['action'][2])
        print('base', item['base_action'][2])
        print('instruction', item['instruction'][2])
        print('qpos', item['qpos'][2])
        print('qvel', item['qvel'][2])
        print('time 3')
        print('action', item['action'][3])
        print('base', item['base_action'][3])
        print('instruction', item['instruction'][3])
        print('qpos', item['qpos'][3])
        print('qvel', item['qvel'][3])


2024-04-19 21:01:38.981968: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-04-19 21:01:39.033403: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-04-19 21:01:39.033437: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-04-19 21:01:39.034951: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-04-19 21:01:39.044078: I tensorflow/core/platform/cpu_feature_guar

<class 'dlimp.dataset.DLataset'>
successfully loaded dataset
{
    "action": "Shape: (500, 14)",
    "base_action": "Shape: (500, 2)",
    "instruction": "Shape: (500,)",
    "observation": {
        "cam_high": "Shape: (500,)",
        "cam_left_wrist": "Shape: (500,)",
        "cam_right_wrist": "Shape: (500,)"
    },
    "qpos": "Shape: (500, 14)",
    "qvel": "Shape: (500, 14)",
    "terminate_episode": "Shape: (500,)"
}
time 0
action tf.Tensor(
[-0.08106327  0.34542656  0.37212944 -0.38548088  0.06618595  0.05970097
  0.16994476  0.08297062  0.00247955  0.00858307 -0.09288883  0.01850128
  0.09098148 -0.03890991], shape=(14,), dtype=float32)
base tf.Tensor([0. 0.], shape=(2,), dtype=float32)
instruction tf.Tensor(b'Insert the cube into the slot.', shape=(), dtype=string)
qpos tf.Tensor(
[-0.06580448  0.31681538  0.33321857 -0.34466362  0.02994537  0.05855656
 -0.02918243  0.08220768  0.00476837  0.00858307 -0.11005592  0.01583099
  0.05245304 -0.09479713], shape=(14,), dtype=float