In [1]:
from octo.data.cobot.standard_dataload import load_dataset_from_tfrecords, load_dataset_from_hdf5
from octo.data.utils.format import pytree_display
from dlimp.dataset import _wrap


dataset_path = '/root/autodl-tmp/cobot_magic'

if __name__ == '__main__':
    dataset = _wrap(load_dataset_from_hdf5, False)(dataset_path)
    print(type(dataset))
    print('successfully loaded dataset')
    for item in dataset.take(1):
        pytree_display(item)
        print('time 0')
        print('action', item['action'][0])
        print('base', item['base_action'][0])
        print('instruction', item['instruction'][0])
        print('qpos', item['qpos'][0])
        print('qvel', item['qvel'][0])
        print('time 1')
        print('action', item['action'][1])
        print('base', item['base_action'][1])
        print('instruction', item['instruction'][1])
        print('qpos', item['qpos'][1])
        print('qvel', item['qvel'][1])
        print('time 2')
        print('action', item['action'][2])
        print('base', item['base_action'][2])
        print('instruction', item['instruction'][2])
        print('qpos', item['qpos'][2])
        print('qvel', item['qvel'][2])
        print('time 3')
        print('action', item['action'][3])
        print('base', item['base_action'][3])
        print('instruction', item['instruction'][3])
        print('qpos', item['qpos'][3])
        print('qvel', item['qvel'][3])


2024-04-18 21:40:12.253910: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-04-18 21:40:12.298975: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-04-18 21:40:12.299011: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-04-18 21:40:12.300671: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-04-18 21:40:12.310263: I tensorflow/core/platform/cpu_feature_guar

<class 'dlimp.dataset.DLataset'>
successfully loaded dataset
{
    "action": "Shape: (500, 14)",
    "base_action": "Shape: (500, 2)",
    "instruction": "Shape: (500,)",
    "observation": {
        "cam_high": "Shape: (500,)",
        "cam_left_wrist": "Shape: (500,)",
        "cam_right_wrist": "Shape: (500,)"
    },
    "qpos": "Shape: (500, 14)",
    "qvel": "Shape: (500, 14)",
    "terminate_episode": "Shape: (500,)"
}
time 0
action tf.Tensor(
[-0.14209938  0.16308117  0.27981186 -0.20542431 -0.07877445  0.03299809
  0.06351471  0.11348915  0.00286102  0.07152653 -0.38166618  0.1829176
  0.03681278 -0.00686646], shape=(14,), dtype=float32)
base tf.Tensor([0. 0.], shape=(2,), dtype=float32)
instruction tf.Tensor(b'Insert the cube into the slot.', shape=(), dtype=string)
qpos tf.Tensor(
[-0.13446999  0.09975624  0.17681408 -0.21839428 -0.08106327  0.0391016
 -0.06694889  0.11577797  0.00553131  0.07076359 -0.3889141   0.17643261
  0.03986454 -0.07953739], shape=(14,), dtype=float32